version: '3'

vars:
  PROJECT_DIR: "{{.TASKFILE_DIR}}"
  SCRIPT_DIR: "{{.PROJECT_DIR}}/scripts"
  LOG_DIR: "{{.PROJECT_DIR}}/logs"

  # Metadata CIS Benchmark
  ID: "K05"
  NAMA: "Pengaturan Ciphers SSH yang Aman"
  KODE_CIS: "5.1.6"
  CIS_JUDUL: "5.1.6 Ensure sshd Ciphers are configured"
  DESKRIPSI: |
    Aturan keamanan untuk memastikan SSH hanya menggunakan 
    algoritma enkripsi (cipher) yang aman dan sesuai standar 
    saat melakukan komunikasi. Fungsinya untuk melindungi data 
    yang dikirim antara client dan server SSH agar tidak mudah 
    dibaca atau disadap oleh pihak yang tidak berwenang.
  RISIKO: "BERISIKO"
  KATEGORI: "SSH"
  AUDIT_ONLY: false

tasks:
  # Task internal untuk memastikan folder logs/ selalu ada
  init-log-dir:
    internal: true
    cmds:
      - mkdir -p {{.LOG_DIR}}

  # 1. Audit SSH Ciphers Configuration
  audit:
    desc: "Menjalankan audit konfigurasi SSH Ciphers"
    deps: [init-log-dir]
    cmds:
      - sudo python3 {{.SCRIPT_DIR}}/audit.py

  # 2. Hardening SSH Ciphers (Terapkan algoritma kriptografi yang kuat)
  hardening:
    desc: "Menerapkan konfigurasi Ciphers terenkripsi kuat pada SSH"
    deps: [init-log-dir]
    cmds:
      - sudo python3 {{.SCRIPT_DIR}}/hardening.py

  # 3. Rollback SSH Ciphers (Mengembalikan parameter Ciphers ke kondisi awal)
  rollback:
    desc: "Mengembalikan konfigurasi Ciphers SSH ke nilai default/kondisi sebelum hardening"
    deps: [init-log-dir]
    cmds:
      - sudo python3 {{.SCRIPT_DIR}}/rollback.py