version: '3'

vars:
  PROJECT_DIR: "{{.TASKFILE_DIR}}"
  SCRIPT_DIR: "{{.PROJECT_DIR}}/scripts"
  LOG_DIR: "{{.PROJECT_DIR}}/logs"

  # Metadata CIS Benchmark
  ID: "K10"
  NAMA: "Pengaturan Kebijakan Default UFW Firewall"
  KODE_CIS: "4.2.7"
  CIS_JUDUL: "4.2.7 Ensure ufw default deny firewall policy"
  RISIKO: "BERISIKO"
  KATEGORI: "Firewall"
  AUDIT_ONLY: true

tasks:
  # Task internal untuk memastikan folder logs/ selalu ada
  init-log-dir:
    internal: true
    cmds:
      - mkdir -p {{.LOG_DIR}}

  # Audit status kebijakan default UFW
  audit:
    desc: "Menjalankan audit kebijakan default UFW firewall"
    deps: [init-log-dir]
    cmds:
      - sudo python3 {{.SCRIPT_DIR}}/audit.py