version: '3'

vars:
  PROJECT_DIR: "{{.TASKFILE_DIR}}"
  SCRIPT_DIR: "{{.PROJECT_DIR}}/scripts"
  LOG_DIR: "{{.PROJECT_DIR}}/logs"

  # Metadata CIS Benchmark
  ID: "K09"
  NAMA: "Memastikan Layanan UFW Aktif"
  KODE_CIS: "4.2.3"
  CIS_JUDUL: "4.2.3 Ensure ufw service is enabled"
  DESKRIPSI: |
    Aturan keamanan untuk memastikan UFW (Uncomplicated Firewall) 
    aktif pada sistem dan berjalan sebagai firewall. Fungsinya 
    untuk mengontrol lalu lintas jaringan masuk dan keluar 
    berdasarkan aturan yang ditentukan, sehingga dapat membatasi 
    akses yang tidak diperlukan ke server.
  RISIKO: "BERISIKO"
  KATEGORI: "Firewall"
  AUDIT_ONLY: true

tasks:
  # Task internal untuk memastikan folder logs/ selalu ada
  init-log-dir:
    internal: true
    cmds:
      - mkdir -p {{.LOG_DIR}}

  # Audit status ufw service (enabled & active)
  audit:
    desc: "Menjalankan audit status layanan ufw"
    deps: [init-log-dir]
    cmds:
      - sudo python3 {{.SCRIPT_DIR}}/audit.py